# イベント用ディレクトリ構造作成の設定ファイル
# `deno task init` を使うか、このファイルをコピーして distribution.config.toml として使用してください
# このコメントは削除しても問題ありません、

[[events]]
date = "20251012"
event_name = "アコスタATC"

[[events.models]]
name = "モデルA"
outreach = true
sns = "https://twitter.com/example_a"
download_url = "" # Google Driveアップロード後に自動入力
message = "" # 配布メッセージ生成ツール実行後に自動入力
recipient_id = "" # XのユーザーID（アップロード時に自動入力、再アップロード時に使用）

[[events.models]]
name = "モデルB"
outreach = false
sns = "https://twitter.com/example_b"
download_url = ""
message = ""
recipient_id = ""

[[events.models]]
name = "モデルC"
outreach = false
sns = ""
download_url = ""
message = ""
recipient_id = ""

[[events.models]]
name = "モデルD"
outreach = true
sns = ""
download_url = ""
message = ""
recipient_id = ""
